[projects."/Users/leroysalih/nodejs/planner-005"]
trust_level = "trusted"

experimental_use_rmcp_client = true

[mcp_servers.supabase_local]
url = "http://localhost:54321/mcp?read_only=true"
startup_timeout_sec = 10
tool_timeout_sec = 120
