-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN; 
 CREATE TABLE IF NOT EXISTS public.pupil_activity_feedback
(
    feedback_id uuid NOT NULL DEFAULT gen_random_uuid(),
    activity_id text COLLATE pg_catalog."default" NOT NULL,
    pupil_id text COLLATE pg_catalog."default" NOT NULL,
    submission_id text COLLATE pg_catalog."default",
    source text COLLATE pg_catalog."default" NOT NULL,
    score numeric,
    feedback_text text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by text COLLATE pg_catalog."default",
    CONSTRAINT pupil_activity_feedback_pkey PRIMARY KEY (feedback_id),
    CONSTRAINT pupil_activity_feedback_activity_id_fkey FOREIGN KEY (activity_id)
        REFERENCES public.activities (activity_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT pupil_activity_feedback_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES public.profiles (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT pupil_activity_feedback_pupil_id_fkey FOREIGN KEY (pupil_id)
        REFERENCES public.profiles (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT pupil_activity_feedback_submission_id_fkey FOREIGN KEY (submission_id)
        REFERENCES public.submissions (submission_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT pupil_activity_feedback_score_range CHECK (score IS NULL OR score >= 0::numeric AND score <= 1::numeric),
    CONSTRAINT pupil_activity_feedback_source_check CHECK (source = ANY (ARRAY['teacher'::text, 'auto'::text, 'ai'::text]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pupil_activity_feedback
    OWNER to postgres;

ALTER TABLE IF EXISTS public.pupil_activity_feedback
    ENABLE ROW LEVEL SECURITY;

GRANT INSERT, SELECT ON TABLE public.pupil_activity_feedback TO authenticated;

GRANT ALL ON TABLE public.pupil_activity_feedback TO postgres;
CREATE INDEX IF NOT EXISTS idx_pupil_activity_feedback_activity_pupil_created_at
    ON public.pupil_activity_feedback USING btree
    (activity_id COLLATE pg_catalog."default" ASC NULLS LAST, pupil_id COLLATE pg_catalog."default" ASC NULLS LAST, created_at DESC NULLS FIRST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_pupil_activity_feedback_submission
    ON public.pupil_activity_feedback USING btree
    (submission_id COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
CREATE POLICY "All Athenticated can Update"
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR UPDATE
    TO authenticated, authenticator
    USING (true)
    WITH CHECK (true);
CREATE POLICY "All Authenticated can Insert"
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR INSERT
    TO authenticated
    WITH CHECK (true);
CREATE POLICY "All Authenticated can Select"
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR SELECT
    TO authenticated
    USING (true);
CREATE POLICY "All authenticated can delete"
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR DELETE
    TO authenticated
    USING (true);
CREATE POLICY insert_pupil_activity_feedback_for_self_or_teacher
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR INSERT
    TO public
    WITH CHECK (((auth.role() = 'service_role'::text) OR (pupil_id = (auth.uid())::text) OR (EXISTS ( SELECT 1
   FROM profiles pr
  WHERE ((pr.user_id = (auth.uid())::text) AND COALESCE(pr.is_teacher, false))))));
CREATE POLICY select_pupil_activity_feedback_for_self_or_teacher
    ON public.pupil_activity_feedback
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (((auth.role() = 'service_role'::text) OR (pupil_id = (auth.uid())::text) OR (EXISTS ( SELECT 1
   FROM profiles pr
  WHERE ((pr.user_id = (auth.uid())::text) AND COALESCE(pr.is_teacher, false))))));
ALTER TABLE IF EXISTS public.group_membership
    OWNER TO postgres;

REVOKE ALL ON TABLE public.group_membership FROM anon;
REVOKE ALL ON TABLE public.group_membership FROM authenticated;
REVOKE ALL ON TABLE public.group_membership FROM postgres;
REVOKE ALL ON TABLE public.group_membership FROM service_role;
REVOKE ALL ON TABLE public.group_membership FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.group_membership TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.group_membership TO authenticated;

GRANT ALL ON TABLE public.group_membership TO postgres;

GRANT ALL ON TABLE public.group_membership TO service_role;
ALTER TABLE IF EXISTS public.lessons_learning_objective
    OWNER TO postgres;

REVOKE ALL ON TABLE public.lessons_learning_objective FROM anon;
REVOKE ALL ON TABLE public.lessons_learning_objective FROM authenticated;
REVOKE ALL ON TABLE public.lessons_learning_objective FROM postgres;
REVOKE ALL ON TABLE public.lessons_learning_objective FROM service_role;
REVOKE ALL ON TABLE public.lessons_learning_objective FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lessons_learning_objective TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lessons_learning_objective TO authenticated;

GRANT ALL ON TABLE public.lessons_learning_objective TO postgres;

GRANT ALL ON TABLE public.lessons_learning_objective TO service_role;
ALTER TABLE IF EXISTS public.units
    OWNER TO postgres;

REVOKE ALL ON TABLE public.units FROM anon;
REVOKE ALL ON TABLE public.units FROM authenticated;
REVOKE ALL ON TABLE public.units FROM postgres;
REVOKE ALL ON TABLE public.units FROM service_role;
REVOKE ALL ON TABLE public.units FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.units TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.units TO authenticated;

GRANT ALL ON TABLE public.units TO postgres;

GRANT ALL ON TABLE public.units TO service_role;
ALTER TABLE IF EXISTS public.submissions
    OWNER TO postgres;

REVOKE ALL ON TABLE public.submissions FROM anon;
REVOKE ALL ON TABLE public.submissions FROM authenticated;
REVOKE ALL ON TABLE public.submissions FROM postgres;
REVOKE ALL ON TABLE public.submissions FROM service_role;
REVOKE ALL ON TABLE public.submissions FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.submissions TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.submissions TO authenticated;

GRANT ALL ON TABLE public.submissions TO postgres;

GRANT ALL ON TABLE public.submissions TO service_role;
ALTER TABLE IF EXISTS public.activity_success_criteria
    OWNER TO postgres;

ALTER TABLE IF EXISTS public.activity_success_criteria
    ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.activity_success_criteria FROM anon;
REVOKE ALL ON TABLE public.activity_success_criteria FROM authenticated;
REVOKE ALL ON TABLE public.activity_success_criteria FROM postgres;
REVOKE ALL ON TABLE public.activity_success_criteria FROM service_role;
REVOKE ALL ON TABLE public.activity_success_criteria FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.activity_success_criteria TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.activity_success_criteria TO authenticated;

GRANT ALL ON TABLE public.activity_success_criteria TO postgres;

GRANT ALL ON TABLE public.activity_success_criteria TO service_role;

CREATE POLICY "Allow All to authenticated"
    ON public.activity_success_criteria
    AS PERMISSIVE
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);


ALTER TABLE IF EXISTS public.n8n_chat_histories
    OWNER TO postgres;

REVOKE ALL ON TABLE public.n8n_chat_histories FROM anon;
REVOKE ALL ON TABLE public.n8n_chat_histories FROM authenticated;
REVOKE ALL ON TABLE public.n8n_chat_histories FROM postgres;
REVOKE ALL ON TABLE public.n8n_chat_histories FROM service_role;
REVOKE ALL ON TABLE public.n8n_chat_histories FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.n8n_chat_histories TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.n8n_chat_histories TO authenticated;

GRANT ALL ON TABLE public.n8n_chat_histories TO postgres;

GRANT ALL ON TABLE public.n8n_chat_histories TO service_role;
ALTER TABLE IF EXISTS public.success_criteria_units
    OWNER TO postgres;

REVOKE ALL ON TABLE public.success_criteria_units FROM anon;
REVOKE ALL ON TABLE public.success_criteria_units FROM authenticated;
REVOKE ALL ON TABLE public.success_criteria_units FROM postgres;
REVOKE ALL ON TABLE public.success_criteria_units FROM service_role;
REVOKE ALL ON TABLE public.success_criteria_units FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.success_criteria_units TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.success_criteria_units TO authenticated;

GRANT ALL ON TABLE public.success_criteria_units TO postgres;

GRANT ALL ON TABLE public.success_criteria_units TO service_role;
ALTER TABLE IF EXISTS public.learning_objectives
    OWNER TO postgres;

REVOKE ALL ON TABLE public.learning_objectives FROM anon;
REVOKE ALL ON TABLE public.learning_objectives FROM authenticated;
REVOKE ALL ON TABLE public.learning_objectives FROM postgres;
REVOKE ALL ON TABLE public.learning_objectives FROM service_role;
REVOKE ALL ON TABLE public.learning_objectives FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.learning_objectives TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.learning_objectives TO authenticated;

GRANT ALL ON TABLE public.learning_objectives TO postgres;

GRANT ALL ON TABLE public.learning_objectives TO service_role;
ALTER TABLE IF EXISTS public.report_pupil_feedback_cache
    OWNER TO postgres;

REVOKE ALL ON TABLE public.report_pupil_feedback_cache FROM anon;
REVOKE ALL ON TABLE public.report_pupil_feedback_cache FROM authenticated;
REVOKE ALL ON TABLE public.report_pupil_feedback_cache FROM postgres;
REVOKE ALL ON TABLE public.report_pupil_feedback_cache FROM service_role;
REVOKE ALL ON TABLE public.report_pupil_feedback_cache FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_feedback_cache TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_feedback_cache TO authenticated;

GRANT ALL ON TABLE public.report_pupil_feedback_cache TO postgres;

GRANT ALL ON TABLE public.report_pupil_feedback_cache TO service_role;
ALTER TABLE IF EXISTS public.subjects
    OWNER TO postgres;

REVOKE ALL ON TABLE public.subjects FROM anon;
REVOKE ALL ON TABLE public.subjects FROM authenticated;
REVOKE ALL ON TABLE public.subjects FROM postgres;
REVOKE ALL ON TABLE public.subjects FROM service_role;
REVOKE ALL ON TABLE public.subjects FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.subjects TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.subjects TO authenticated;

GRANT ALL ON TABLE public.subjects TO postgres;

GRANT ALL ON TABLE public.subjects TO service_role;
ALTER TABLE IF EXISTS public.lesson_links
    OWNER TO postgres;

REVOKE ALL ON TABLE public.lesson_links FROM anon;
REVOKE ALL ON TABLE public.lesson_links FROM authenticated;
REVOKE ALL ON TABLE public.lesson_links FROM postgres;
REVOKE ALL ON TABLE public.lesson_links FROM service_role;
REVOKE ALL ON TABLE public.lesson_links FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_links TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_links TO authenticated;

GRANT ALL ON TABLE public.lesson_links TO postgres;

GRANT ALL ON TABLE public.lesson_links TO service_role;
ALTER TABLE IF EXISTS public.groups
    OWNER TO postgres;

REVOKE ALL ON TABLE public.groups FROM anon;
REVOKE ALL ON TABLE public.groups FROM authenticated;
REVOKE ALL ON TABLE public.groups FROM postgres;
REVOKE ALL ON TABLE public.groups FROM service_role;
REVOKE ALL ON TABLE public.groups FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.groups TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.groups TO authenticated;

GRANT ALL ON TABLE public.groups TO postgres;

GRANT ALL ON TABLE public.groups TO service_role;
ALTER TABLE IF EXISTS public.success_criteria
    OWNER TO postgres;

REVOKE ALL ON TABLE public.success_criteria FROM anon;
REVOKE ALL ON TABLE public.success_criteria FROM authenticated;
REVOKE ALL ON TABLE public.success_criteria FROM postgres;
REVOKE ALL ON TABLE public.success_criteria FROM service_role;
REVOKE ALL ON TABLE public.success_criteria FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.success_criteria TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.success_criteria TO authenticated;

GRANT ALL ON TABLE public.success_criteria TO postgres;

GRANT ALL ON TABLE public.success_criteria TO service_role;
ALTER TABLE IF EXISTS public.assessment_objectives
    OWNER TO postgres;

ALTER TABLE IF EXISTS public.assessment_objectives
    ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.assessment_objectives FROM anon;
REVOKE ALL ON TABLE public.assessment_objectives FROM authenticated;
REVOKE ALL ON TABLE public.assessment_objectives FROM postgres;
REVOKE ALL ON TABLE public.assessment_objectives FROM service_role;
REVOKE ALL ON TABLE public.assessment_objectives FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.assessment_objectives TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.assessment_objectives TO authenticated;

GRANT ALL ON TABLE public.assessment_objectives TO postgres;

GRANT ALL ON TABLE public.assessment_objectives TO service_role;

CREATE POLICY "Allow Authenticated"
    ON public.assessment_objectives
    AS PERMISSIVE
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);


ALTER TABLE IF EXISTS public.activities
    OWNER TO postgres;

ALTER TABLE IF EXISTS public.activities
    ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.activities FROM anon;
REVOKE ALL ON TABLE public.activities FROM authenticated;
REVOKE ALL ON TABLE public.activities FROM postgres;
REVOKE ALL ON TABLE public.activities FROM service_role;
REVOKE ALL ON TABLE public.activities FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.activities TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.activities TO authenticated;

GRANT ALL ON TABLE public.activities TO postgres;

GRANT ALL ON TABLE public.activities TO service_role;

CREATE POLICY "Allow all to authenticated"
    ON public.activities
    AS PERMISSIVE
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);


ALTER TABLE IF EXISTS public.report_pupil_cache
    OWNER TO postgres;

REVOKE ALL ON TABLE public.report_pupil_cache FROM anon;
REVOKE ALL ON TABLE public.report_pupil_cache FROM authenticated;
REVOKE ALL ON TABLE public.report_pupil_cache FROM postgres;
REVOKE ALL ON TABLE public.report_pupil_cache FROM service_role;
REVOKE ALL ON TABLE public.report_pupil_cache FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_cache TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_cache TO authenticated;

GRANT ALL ON TABLE public.report_pupil_cache TO postgres;

GRANT ALL ON TABLE public.report_pupil_cache TO service_role;
ALTER TABLE IF EXISTS public.short_text_feedback_events
    OWNER TO postgres;

REVOKE ALL ON TABLE public.short_text_feedback_events FROM anon;
REVOKE ALL ON TABLE public.short_text_feedback_events FROM authenticated;
REVOKE ALL ON TABLE public.short_text_feedback_events FROM postgres;
REVOKE ALL ON TABLE public.short_text_feedback_events FROM service_role;
REVOKE ALL ON TABLE public.short_text_feedback_events FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.short_text_feedback_events TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.short_text_feedback_events TO authenticated;

GRANT ALL ON TABLE public.short_text_feedback_events TO postgres;

GRANT ALL ON TABLE public.short_text_feedback_events TO service_role;
ALTER TABLE IF EXISTS public.lesson_success_criteria
    OWNER TO postgres;

REVOKE ALL ON TABLE public.lesson_success_criteria FROM anon;
REVOKE ALL ON TABLE public.lesson_success_criteria FROM authenticated;
REVOKE ALL ON TABLE public.lesson_success_criteria FROM postgres;
REVOKE ALL ON TABLE public.lesson_success_criteria FROM service_role;
REVOKE ALL ON TABLE public.lesson_success_criteria FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_success_criteria TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_success_criteria TO authenticated;

GRANT ALL ON TABLE public.lesson_success_criteria TO postgres;

GRANT ALL ON TABLE public.lesson_success_criteria TO service_role;
ALTER TABLE IF EXISTS public.lesson_assignments
    OWNER TO postgres;

REVOKE ALL ON TABLE public.lesson_assignments FROM anon;
REVOKE ALL ON TABLE public.lesson_assignments FROM authenticated;
REVOKE ALL ON TABLE public.lesson_assignments FROM postgres;
REVOKE ALL ON TABLE public.lesson_assignments FROM service_role;
REVOKE ALL ON TABLE public.lesson_assignments FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_assignments TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lesson_assignments TO authenticated;

GRANT ALL ON TABLE public.lesson_assignments TO postgres;

GRANT ALL ON TABLE public.lesson_assignments TO service_role;
ALTER TABLE IF EXISTS public.curricula
    OWNER TO postgres;

REVOKE ALL ON TABLE public.curricula FROM anon;
REVOKE ALL ON TABLE public.curricula FROM authenticated;
REVOKE ALL ON TABLE public.curricula FROM postgres;
REVOKE ALL ON TABLE public.curricula FROM service_role;
REVOKE ALL ON TABLE public.curricula FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.curricula TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.curricula TO authenticated;

GRANT ALL ON TABLE public.curricula TO postgres;

GRANT ALL ON TABLE public.curricula TO service_role;
ALTER TABLE IF EXISTS public.assignments
    OWNER TO postgres;

REVOKE ALL ON TABLE public.assignments FROM anon;
REVOKE ALL ON TABLE public.assignments FROM authenticated;
REVOKE ALL ON TABLE public.assignments FROM postgres;
REVOKE ALL ON TABLE public.assignments FROM service_role;
REVOKE ALL ON TABLE public.assignments FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.assignments TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.assignments TO authenticated;

GRANT ALL ON TABLE public.assignments TO postgres;

GRANT ALL ON TABLE public.assignments TO service_role;
ALTER TABLE IF EXISTS public.lessons
    OWNER TO postgres;

REVOKE ALL ON TABLE public.lessons FROM anon;
REVOKE ALL ON TABLE public.lessons FROM authenticated;
REVOKE ALL ON TABLE public.lessons FROM postgres;
REVOKE ALL ON TABLE public.lessons FROM service_role;
REVOKE ALL ON TABLE public.lessons FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lessons TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.lessons TO authenticated;

GRANT ALL ON TABLE public.lessons TO postgres;

GRANT ALL ON TABLE public.lessons TO service_role;
ALTER TABLE IF EXISTS public.documents
    OWNER TO postgres;

REVOKE ALL ON TABLE public.documents FROM anon;
REVOKE ALL ON TABLE public.documents FROM authenticated;
REVOKE ALL ON TABLE public.documents FROM postgres;
REVOKE ALL ON TABLE public.documents FROM service_role;
REVOKE ALL ON TABLE public.documents FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.documents TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.documents TO authenticated;

GRANT ALL ON TABLE public.documents TO postgres;

GRANT ALL ON TABLE public.documents TO service_role;
ALTER TABLE IF EXISTS public.profiles
    OWNER TO postgres;

REVOKE ALL ON TABLE public.profiles FROM anon;
REVOKE ALL ON TABLE public.profiles FROM authenticated;
REVOKE ALL ON TABLE public.profiles FROM postgres;
REVOKE ALL ON TABLE public.profiles FROM service_role;
REVOKE ALL ON TABLE public.profiles FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.profiles TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;
ALTER TABLE IF EXISTS public.feedback
    OWNER TO postgres;

REVOKE ALL ON TABLE public.feedback FROM anon;
REVOKE ALL ON TABLE public.feedback FROM authenticated;
REVOKE ALL ON TABLE public.feedback FROM postgres;
REVOKE ALL ON TABLE public.feedback FROM service_role;
REVOKE ALL ON TABLE public.feedback FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.feedback TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.feedback TO authenticated;

GRANT ALL ON TABLE public.feedback TO postgres;

GRANT ALL ON TABLE public.feedback TO service_role;
ALTER TABLE IF EXISTS public.report_pupil_unit_summaries
    OWNER TO postgres;

REVOKE ALL ON TABLE public.report_pupil_unit_summaries FROM anon;
REVOKE ALL ON TABLE public.report_pupil_unit_summaries FROM authenticated;
REVOKE ALL ON TABLE public.report_pupil_unit_summaries FROM postgres;
REVOKE ALL ON TABLE public.report_pupil_unit_summaries FROM service_role;
REVOKE ALL ON TABLE public.report_pupil_unit_summaries FROM supabase_admin;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_unit_summaries TO anon;

GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE public.report_pupil_unit_summaries TO authenticated;

GRANT ALL ON TABLE public.report_pupil_unit_summaries TO postgres;

GRANT ALL ON TABLE public.report_pupil_unit_summaries TO service_role;
ALTER FUNCTION public.match_documents(vector, integer, jsonb)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM anon;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM authenticated;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM postgres;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM service_role;

REVOKE ALL ON FUNCTION public.match_documents(vector, integer, jsonb) FROM supabase_admin;
ALTER FUNCTION public.reports_recalculate_pupil_cache(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM anon;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM postgres;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM service_role;

REVOKE ALL ON FUNCTION public.reports_recalculate_pupil_cache(text) FROM supabase_admin;
ALTER FUNCTION public.safe_numeric(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM anon;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM postgres;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM service_role;

REVOKE ALL ON FUNCTION public.safe_numeric(text) FROM supabase_admin;
ALTER FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM anon;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM authenticated;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM postgres;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM service_role;

REVOKE ALL ON FUNCTION public.reports_store_pupil_unit_summaries(text, jsonb) FROM supabase_admin;
ALTER FUNCTION public.clamp_score(numeric)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM anon;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM authenticated;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM postgres;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM service_role;

REVOKE ALL ON FUNCTION public.clamp_score(numeric) FROM supabase_admin;
ALTER FUNCTION public.lesson_assignment_score_summaries(jsonb)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM anon;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM authenticated;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM postgres;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM service_role;

REVOKE ALL ON FUNCTION public.lesson_assignment_score_summaries(jsonb) FROM supabase_admin;
ALTER FUNCTION public.reports_get_prepared_report_dataset(text, text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM anon;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM authenticated;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM postgres;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM service_role;

REVOKE ALL ON FUNCTION public.reports_get_prepared_report_dataset(text, text) FROM supabase_admin;
ALTER FUNCTION public.assignments_bootstrap()
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM anon;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM authenticated;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM postgres;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM service_role;

REVOKE ALL ON FUNCTION public.assignments_bootstrap() FROM supabase_admin;
ALTER FUNCTION public.pupil_lessons_summary_bootstrap(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM anon;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM postgres;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM service_role;

REVOKE ALL ON FUNCTION public.pupil_lessons_summary_bootstrap(text) FROM supabase_admin;
ALTER FUNCTION public.compute_submission_base_score(json, text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM anon;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM authenticated;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM postgres;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM service_role;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(json, text) FROM supabase_admin;
ALTER FUNCTION public.pupil_lessons_detail_bootstrap(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM anon;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM postgres;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM service_role;

REVOKE ALL ON FUNCTION public.pupil_lessons_detail_bootstrap(text) FROM supabase_admin;
ALTER FUNCTION public.reports_list_pupils_with_groups()
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM anon;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM authenticated;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM postgres;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM service_role;

REVOKE ALL ON FUNCTION public.reports_list_pupils_with_groups() FROM supabase_admin;
ALTER FUNCTION public.compute_submission_base_score(jsonb, text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM anon;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM authenticated;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM postgres;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM service_role;

REVOKE ALL ON FUNCTION public.compute_submission_base_score(jsonb, text) FROM supabase_admin;
ALTER FUNCTION public.lesson_detail_bootstrap(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM anon;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM postgres;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM service_role;

REVOKE ALL ON FUNCTION public.lesson_detail_bootstrap(text) FROM supabase_admin;
ALTER FUNCTION public.lesson_reference_bootstrap(text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM anon;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM authenticated;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM postgres;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM service_role;

REVOKE ALL ON FUNCTION public.lesson_reference_bootstrap(text) FROM supabase_admin;
ALTER FUNCTION public.get_latest_short_text_submission(text, text)
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM PUBLIC;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM anon;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM authenticated;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM postgres;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM service_role;

REVOKE ALL ON FUNCTION public.get_latest_short_text_submission(text, text) FROM supabase_admin;
ALTER FUNCTION public.set_learning_objectives_order_by()
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM anon;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM authenticated;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM postgres;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM service_role;

REVOKE ALL ON FUNCTION public.set_learning_objectives_order_by() FROM supabase_admin;
ALTER FUNCTION public.set_lessons_order_by()
    OWNER TO postgres;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM anon;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM authenticated;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM postgres;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM service_role;

REVOKE ALL ON FUNCTION public.set_lessons_order_by() FROM supabase_admin;
ALTER SEQUENCE IF EXISTS public.feedback_id_seq
    OWNER TO postgres;


REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM anon;
REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM authenticated;
REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM postgres;
REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM service_role;
REVOKE ALL ON SEQUENCE public.feedback_id_seq FROM supabase_admin;
GRANT USAGE, SELECT ON SEQUENCE public.feedback_id_seq TO anon;

GRANT USAGE, SELECT ON SEQUENCE public.feedback_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.feedback_id_seq TO postgres;

GRANT USAGE, SELECT ON SEQUENCE public.feedback_id_seq TO service_role;


ALTER SEQUENCE IF EXISTS public.n8n_chat_histories_id_seq
    OWNER TO postgres;


REVOKE ALL ON SEQUENCE public.n8n_chat_histories_id_seq FROM anon;
REVOKE ALL ON SEQUENCE public.n8n_chat_histories_id_seq FROM authenticated;
REVOKE ALL ON SEQUENCE public.n8n_chat_histories_id_seq FROM postgres;
REVOKE ALL ON SEQUENCE public.n8n_chat_histories_id_seq FROM service_role;
REVOKE ALL ON SEQUENCE public.n8n_chat_histories_id_seq FROM supabase_admin;
GRANT USAGE, SELECT ON SEQUENCE public.n8n_chat_histories_id_seq TO anon;

GRANT USAGE, SELECT ON SEQUENCE public.n8n_chat_histories_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.n8n_chat_histories_id_seq TO postgres;

GRANT USAGE, SELECT ON SEQUENCE public.n8n_chat_histories_id_seq TO service_role;


ALTER SEQUENCE IF EXISTS public.documents_id_seq
    OWNER TO postgres;


REVOKE ALL ON SEQUENCE public.documents_id_seq FROM anon;
REVOKE ALL ON SEQUENCE public.documents_id_seq FROM authenticated;
REVOKE ALL ON SEQUENCE public.documents_id_seq FROM postgres;
REVOKE ALL ON SEQUENCE public.documents_id_seq FROM service_role;
REVOKE ALL ON SEQUENCE public.documents_id_seq FROM supabase_admin;
GRANT USAGE, SELECT ON SEQUENCE public.documents_id_seq TO anon;

GRANT USAGE, SELECT ON SEQUENCE public.documents_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.documents_id_seq TO postgres;

GRANT USAGE, SELECT ON SEQUENCE public.documents_id_seq TO service_role;


ALTER SEQUENCE IF EXISTS public.submissions_replication_pk_seq
    OWNER TO postgres;


REVOKE ALL ON SEQUENCE public.submissions_replication_pk_seq FROM anon;
REVOKE ALL ON SEQUENCE public.submissions_replication_pk_seq FROM authenticated;
REVOKE ALL ON SEQUENCE public.submissions_replication_pk_seq FROM postgres;
REVOKE ALL ON SEQUENCE public.submissions_replication_pk_seq FROM service_role;
REVOKE ALL ON SEQUENCE public.submissions_replication_pk_seq FROM supabase_admin;
GRANT USAGE, SELECT ON SEQUENCE public.submissions_replication_pk_seq TO anon;

GRANT USAGE, SELECT ON SEQUENCE public.submissions_replication_pk_seq TO authenticated;

GRANT ALL ON SEQUENCE public.submissions_replication_pk_seq TO postgres;

GRANT USAGE, SELECT ON SEQUENCE public.submissions_replication_pk_seq TO service_role;



 END;