name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    - name: Assert secrets are present
      run: |
           [ -z "${{ secrets.TEACHER_EMAIL }}" ] && echo "TEACHER_EMAIL missing" && exit 1 || echo "✅ TEACHER_EMAIL present"
           [ -z "${{ secrets.TEACHER_PASSWORD }}" ] && echo "TEACHER_PASSWORD missing" && exit 1 || echo "✅ TEACHER_PASSWORD present"
    - name: Install dependencies
      run: npm ci --force
    - name: Create tests/.env.test from secrets
      run: |
          mkdir -p tests
          cat > tests/.env.test <<'EOF'
          TEACHER_EMAIL=${{ secrets.TEACHER_EMAIL }}
          TEACHER_PASSWORD=${{ secrets.TEACHER_PASSWORD }}
          TEACHER_NAME=${{ secrets.TEACHER_NAME }}
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}}
          PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_PUBLISHABLE_KEY=${{ secrets.PUBLIC_SUPABASE_PUBLISHABLE_KEY}}
          BASE_URL=${{ vars.TEST_BASE_URL }}
          EOF
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
